DICT_USER_SETTINGS = {
    "ALE": {
        "chunk_size": 30,
        "sys_path": "C:\\Users\\mastrucc\\Documents\\cc_ene_dem",
        "dle_path": "C:\\Users\\mastrucc.IIASA2003\\IIASA\\DLE - Climate impacts and space conditioning\\Data\\input_data\\",
        "isimip_bias_adj_path": "P:\\watxene\\ISIMIP\\ISIMIP3b\\InputData\\climate_updated\\bias-adjusted\\",
        "isimip_ewembi_path": "P:\\watxene\\ISIMIP\\ISIMIP2a_hist\\input\\EWEMBI\\",
        "message_region_map_file": "P:\\ene.model3\\data\\powerplants\\MESSAGE data\\MESSAGEix_country_region_map.xlsx",
        "ar6_snapshot_file": "path\\to\\AR6_Scenarios_Database_World_v1.1.csv",
    },
    "ED": {
        "chunk_size": 360,
        "sys_path": "C:\\github\\cc_ene_dem",
        "dle_path": "C:\\Users\\byers\\IIASA\\DLE - Climate impacts and space conditioning\\Data\\input_data",
        "isimip_bias_adj_path": "P:\\watxene\\ISIMIP\\ISIMIP3b\\InputData\\climate_updated\\bias-adjusted\\",
        "isimip_ewembi_path": "P:\\watxene\\ISIMIP\\ISIMIP2a_hist\\input\\EWEMBI\\",
        "message_region_map_file": "P:\\ene.model\\data\\powerplants\\MESSAGE data\\MESSAGEix_country_region_map.xlsx",
        "ar6_snapshot_file": "C:\\Users\\byers\\IIASA\\IPCC WG3 Chapter 3 - Documents\\IPCC_AR6DB\\snapshots\\snapshot_ar6_public_v1.1\\uploaded\\AR6_Scenarios_Database_World_v1.1.csv",
    },
    "MEAS": {
        "chunk_size": 125,
        "sys_path": "/Users/meas/iiasagit/cc_ene_dem",
        "chilled_data_path": "/Users/meas/Library/CloudStorage/OneDrive-SharedLibraries-IIASA/DLE - Analysis/Climate impacts and space conditioning/Data/chilled",
        "dle_path": "/Users/meas/Library/CloudStorage/OneDrive-SharedLibraries-IIASA/DLE - Analysis/Climate impacts and space conditioning/Data",
        "isimip_bias_adj_path": "/Volumes/mengm.pdrv/watxene/ISIMIP/ISIMIP3b/InputData/climate_updated/bias-adjusted",
        "isimip_ewembi_path": "/Volumes/mengm.pdrv/watxene/ISIMIP/ISIMIP2a_hist/input/EWEMBI",
        "message_region_map_file": "/Volumes/mengm.pdrv/ene.model/data/powerplants/MESSAGE data/MESSAGEix_country_region_map.xlsx",
        "ar6_snapshot_file": "/Users/meas/Documents/data/ar6/1668008312256-AR6_Scenarios_Database_World_v1.1.csv/AR6_Scenarios_Database_World_v1.1.csv",
    },
    "MEAS_EBRO": {
        "chunk_size": 360,
        "sys_path": "H:\\MyDocuments\\repos\\cc_ene_dem",
        "dle_path": "D:\\mengm\\IIASA\\DLE - Data",
        "isimip_bias_adj_path": "P:\\watxene\\ISIMIP\\ISIMIP3b\\InputData\\climate_updated\\bias-adjusted",
        "isimip_ewembi_path": "P:\\watxene\\ISIMIP\\ISIMIP2a_hist\\input\\EWEMBI",
        "message_region_map_file": "P:\\ene.model\\data\\powerplants\\MESSAGE data\\MESSAGEix_country_region_map.xlsx",
        "ar6_snapshot_file": "D:\\mengm\\IIASA\\DLE - Data\\input_data\\AR6_Scenarios_Database_World\\AR6_Scenarios_Database_World_v1.1.csv",
    },
    "MEAS_UNICC": {
        "chunk_size": 450,
        "sys_path": "/home/mengm/repo/message-ix-buildings",
        "project_path": "/projects/chilled",
        "dle_path": "/projects/chilled/data/input_data/",
        "isimip_bias_adj_path": "/pdrive/projects/watxene/ISIMIP/ISIMIP3b/InputData/climate_updated/bias-adjusted",
        "isimip_ewembi_path": "/pdrive/projects/watxene/ISIMIP/ISIMIP2a_hist/input/EWEMBI",
        "message_region_map_file": "/pdrive/projects/ene.model3/data/powerplants/MESSAGE data/MESSAGEix_country_region_map.xlsx",
        "ar6_snapshot_file": "/projects/chilled/data/ar6/1668008312256-AR6_Scenarios_Database_World_v1.1.csv/AR6_Scenarios_Database_World_v1.1.csv",
    },
}
