---
output: reprex::reprex_document
knit: reprex::reprex_render
---

Notebook to run STURM Ouput.

```{r}
library(dplyr)
library(ggplot2)
library(stringr)
library(tidyr)

print(paste("Working directory is:", getwd()))

# Loding figures setttings and functions
source("STURM_output/C00_plots.R")

```

```{r}
scenario <- "EU"
file <- paste0("report_agg_STURM_", scenario, "_resid_region_bld_energy.csv")
file <- paste("STURM_output/results", file, sep = "/")

if (!file.exists(file)) {
  print("Check file name or directory!")
}

save_dir <- paste("STURM_output", "figures", scenario, sep = "/")
print(dir.exists(save_dir))

# Read output files
data <- read.csv(file)
print(summary(data))
print(unique(data$variable))

# Reconstuction flows
flows <- c("cost_renovation_EUR", "n_renovation", "n_out",
  "n_dem", "n_empty")
stp <- 5
data <- data %>%
  mutate(year = ifelse(variable %in% flows, year - stp, year),
         value = ifelse(variable %in% flows, value / stp, value))
```
## Figures 

### Breakdown stock units
#### By fuel types
```{r}
source("STURM_output/C00_plots.R")

data_stock_historic <- read.csv(
  "STURM_output/ressources/stock_historic_data_jrcidees.csv")

t <- data_stock_historic %>%
  rename(resolution = fuel_heat) %>%
  filter(year < 2015)
t_eu <- t %>%
  group_by_at(c("year", "resolution")) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  mutate(region_bld = "EU")
t <- bind_rows(t, t_eu)

temp <- data %>%
  filter(variable == "stock_building") %>%
  filter(resolution %in% names(rename_fuels)) %>%
  select(-c("variable"))

temp <- bind_rows(t, temp)

legend <- FALSE
plot_stacked_areas(temp, "year", "value", "resolution", "region_bld",
                    y_label = "Stock housing units",
                    save_path = paste(save_dir, paste0(scenario, "_share_fuels_stock_countries.png"),
                    sep = "/"), vertical = 2015, percent = FALSE, , legend = legend)

temp <- temp %>%
  filter(region_bld == "EU") %>%
  mutate(value = value / 1e6)

presentation <- TRUE
legend <- FALSE
plot_stacked_areas(temp, "year", "value", "resolution", "region_bld",
                    y_label = "Stock housing units",
                    save_path = paste(save_dir, paste0(scenario, "_share_fuels_stock_eu.png"),
                    sep = "/"), vertical = 2015, percent = FALSE, y_label_suffix = "M",
                    presentation = presentation, legend = legend)

```
#### By energy efficiency
```{r}
temp <- data %>%
  filter(variable == "stock_building") %>%
  filter(resolution %in% names(rename_eneff)) %>%
  select(-c("variable"))

plot_stacked_areas(temp, "year", "value", "resolution", "region_bld",
                    y_label = "Stock housing units",
                    save_path = paste(save_dir, paste0(scenario, "_share_eff_stock_countries.png"),
                    sep = "/"))

temp <- temp %>%
  filter(region_bld == "EU") %>%
  mutate(value = value / 1e6)

presentation <- TRUE
legend <- FALSE
plot_stacked_areas(temp, "year", "value", "resolution", "region_bld",
                    y_label = "Stock housing units",
                    save_path = paste(save_dir, paste0(scenario, "_share_eff_stock_eu.png"),
                    sep = "/"), percent = FALSE, y_label_suffix = "M",
                    presentation = presentation, legend = legend)
```
### Breakdown energy demand
#### By fuel types
```{r}
source("STURM_output/C00_plots.R")

data_consumption_historic <- read.csv(
  "STURM_output/ressources/final_energy_consumption_historic_data_ktoe_jrcidees.csv")

t <- data_consumption_historic %>%
  rename(resolution = fuel_heat) %>%
  # ktoe to TWh
  mutate(value = value * 0.01163) %>%
  filter(year < 2015)
t_eu <- t %>%
  group_by_at(c("year", "resolution")) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  mutate(region_bld = "EU")
t <- bind_rows(t, t_eu)

temp <- data %>%
  filter(variable == "heat_kWh") %>%
  filter(resolution %in% names(rename_fuels)) %>%
  select(-c("variable")) %>%
  # kwh to TWh
  mutate(value = value / 1e9)
temp <- bind_rows(t, temp)

plot_stacked_areas(temp, "year", "value", "resolution", "region_bld",
                    y_label = "Space heating consumption (TWh)",
                    save_path = paste(save_dir, paste0(scenario, "_share_fuels_consumption_countries.png"),
                    sep = "/"), vertical = 2015, percent = FALSE)

presentation <- TRUE
legend <- FALSE
plot_stacked_areas(filter(temp, region_bld == "EU"), "year", "value", "resolution", "region_bld",
                    y_label = "Space heating consumption (TWh)",
                    save_path = paste(save_dir, paste0(scenario, "_share_fuels_consumption_eu.png"),
                    sep = "/"), vertical = 2015, percent = FALSE, y_label_suffix = "TWh",
                    presentation = presentation, legend = legend)

```
#### By energy performance
```{r}
temp <- data %>%
  filter(variable == "heat_kWh") %>%
  filter(resolution %in% names(rename_eneff)) %>%
  select(-c("variable")) %>%
  mutate(value = value / 1e9)


plot_stacked_areas(temp, "year", "value", "resolution", "region_bld",
                    y_label = "Space heating consumption (TWh)",
                    save_path = paste(save_dir, paste0(scenario, "_share_eff_consumption_countries.png"),
                    sep = "/"), percent = FALSE)
  
presentation <- TRUE
legend <- TRUE
plot_stacked_areas(filter(temp, region_bld == "EU"), "year", "value", "resolution", "region_bld",
                    y_label = "Space heating consumption",
                    save_path = paste(save_dir, paste0(scenario, "_share_eff_consumption_eu.png"),
                    sep = "/"), percent = FALSE, y_label_suffix = "TWh",
                    presentation = presentation, legend = legend)
```

### Indicators charts
```{r}
make_plot_lines <- function(data, var, ref, path, y_label = "",
  percent = FALSE, y_label_suffix = NULL) {
  temp <- data %>%
    filter(variable %in% c(var, ref)) %>%
    filter(resolution == "all") %>%
    pivot_wider(id_cols = c(region_bld, year, resolution),
      names_from = variable,
      values_from = value) %>%
    filter(!is.na(.data[[var]])) %>%
    filter(!is.na(.data[[ref]])) %>%
    mutate(value = .data[[var]] / .data[[ref]]) %>%
    select(-c(var, ref, "resolution"))

  if (percent) {
    temp <- temp %>%
      mutate(value = value * 100)
    y_label_suffix <- "%"
  }

  plot_multiple_lines(temp,
          x_column = "year",
          y_column = "value",
          group_column = "region_bld",
          ncol = 4,
          save_path = paste(save_dir, paste0(scenario, path), sep = "/"),
          y_label_suffix = y_label_suffix,
          )
  }

var <- "n_out"
ref <- "stock_building"
path <- "_demolition_rate_countries.png"
make_plot_lines(data, var, ref, path, percent = TRUE)

var <- "n_renovation"
ref <- "stock_building"
path <- "_renovation_rate_countries.png"
make_plot_lines(data, var, ref, path, percent = TRUE)

var <- "heat_kWh"
ref <- "stock_building"
path <- "_kwh_dwelling_countries.png"
make_plot_lines(data, var, ref, pat, y_label_suffix = "kWh/dw")

var <- "heat_kWh"
ref <- "floor_m2"
path <- "_kwh_m2_countries.png"
make_plot_lines(data, var, ref, path, y_label_suffix = "kWh/m2")

var <- "heat_std_kWh"
ref <- "floor_m2"
path <- "_kwh_std_m2_countries.png"
make_plot_lines(data, var, ref, path, y_label_suffix = "kWh/m2")

var <- "heat_tCO2"
ref <- "floor_m2"
path <- "_tCO2_m2_countries.png"
make_plot_lines(data, var, ref, path, y_label_suffix = "tCO2/m2")

temp <- data %>%
  mutate(value = ifelse(variable == "heat_tCO2", value * 1e6, value))

var <- "heat_tCO2"
ref <- "heat_kWh"
path <- "_gCO2_kWh_countries.png"
make_plot_lines(temp, var, ref, path, y_label_suffix = "gCO2/kWh")
```

### Absolute values charts
#### Stock
```{r}
temp <- data %>%
  filter(variable == "stock_building") %>%
  filter(resolution %in% "all") %>%
  select(-c("variable", "resolution")) %>%
  mutate(value = value / 1e6)

plot_multiple_lines(temp,
          x_column = "year",
          y_column = "value",
          group_column = "region_bld",
          ncol = 4,
          y_label = "Stock housing units\nMillion",
          free_y = TRUE,
          save_path = paste(save_dir, paste0(scenario, "_stock_countries.png"), sep = "/"),
          y_label_suffix = "M")
```

#### Space heating consumption
```{r}
temp <- data %>%
  filter(variable == "heat_kWh") %>%
  filter(resolution %in% "all") %>%
  select(-c("variable", "resolution")) %>%
  mutate(value = value / 1e9)

plot_multiple_lines(temp,
          x_column = "year",
          y_column = "value",
          group_column = "region_bld",
          ncol = 4,
          y_label = "Space heating consumption\nTWh",
          free_y = TRUE,
          save_path = paste(save_dir, paste0(scenario, "_twh_countries.png"), sep = "/"),
          y_label_suffix = "TWh")

temp <- data %>%
  filter(variable == "heat_std_kWh") %>%
  filter(resolution %in% "all") %>%
  select(-c("variable", "resolution")) %>%
  mutate(value = value / 1e9)

plot_multiple_lines(temp,
          x_column = "year",
          y_column = "value",
          group_column = "region_bld",
          ncol = 4,
          y_label = "Standard space heating consumption\nTWh",
          free_y = TRUE,
          save_path = paste(save_dir, paste0(scenario, "_twh_std_countries.png"), sep = "/"),
          y_label_suffix = "TWh")


temp <- data %>%
  filter(variable == "heat_kWh") %>%
  filter(resolution %in% "all") %>%
  select(-c("variable", "resolution")) %>%
  mutate(value = value * 3.6 * 1e-6)

plot_multiple_lines(temp,
          x_column = "year",
          y_column = "value",
          group_column = "region_bld",
          ncol = 4,
          y_label = "Space heating consumption\nTJ",
          free_y = TRUE,
          save_path = paste(save_dir, paste0(scenario, "_tj_countries.png"), sep = "/"),
          y_label_suffix = "TJ")

temp <- data %>%
  filter(variable == "heat_kWh") %>%
  filter(resolution %in% "all") %>%
  select(-c("variable", "resolution")) %>%
  mutate(value = value / (11630 * 1e6))

plot_multiple_lines(temp,
          x_column = "year",
          y_column = "value",
          group_column = "region_bld",
          ncol = 4,
          y_label = "Space heating consumption\nMtoe",
          free_y = TRUE,
          save_path = paste(save_dir, paste0(scenario, "_mtoe_countries.png"), sep = "/"),
          y_label_suffix = "Mtoe")
```

#### Emission 
```{r}
temp <- data %>%
  filter(variable == "heat_tCO2") %>%
  filter(resolution %in% "all") %>%
  select(-c("variable", "resolution")) %>%
  mutate(value = value / 1e6)

plot_multiple_lines(temp,
          x_column = "year",
          y_column = "value",
          group_column = "region_bld",
          ncol = 4,
          y_label = "Space heating emission\nMtCO2",
          free_y = TRUE,
          save_path = paste(save_dir, paste0(scenario, "_mtco2_countries.png"), sep = "/"),
          y_label_suffix = "MtCO2")

```

#### Number of renovations, cost renovation and cost heat
```{r}
temp <- data %>%
  filter(variable == "n_renovation") %>%
  filter(resolution %in% "all") %>%
  select(-c("variable", "resolution")) %>%
  mutate(value = value / 1e3)

plot_multiple_lines(temp,
          x_column = "year",
          y_column = "value",
          group_column = "region_bld",
          ncol = 4,
          y_label = "Number of renovations\nThousands",
          free_y = TRUE,
          save_path = paste(save_dir, paste0(scenario, "_renovation_countries.png"), sep = "/"),
          y_label_suffix = "k")

temp <- data %>%
  filter(variable == "cost_renovation_EUR") %>%
  filter(resolution %in% "all") %>%
  select(-c("variable", "resolution")) %>%
  mutate(value = value / 1e9)

plot_multiple_lines(temp,
          x_column = "year",
          y_column = "value",
          group_column = "region_bld",
          ncol = 4,
          y_label = "Cost shell energy renovation\nBillion EUR",
          free_y = TRUE,
          save_path = paste(save_dir, paste0(scenario, "_cost_renovation_countries.png"), sep = "/"),
          y_label_suffix = "B")

temp <- data %>%
  filter(variable == "cost_heat_EUR") %>%
  filter(resolution %in% "all") %>%
  select(-c("variable", "resolution")) %>%
  mutate(value = value / 1e9)

plot_multiple_lines(temp,
          x_column = "year",
          y_column = "value",
          group_column = "region_bld",
          ncol = 4,
          y_label = "Cost heat\nBillion EUR",
          free_y = TRUE,
          save_path = paste(save_dir, paste0(scenario, "_cost_heat_countries.png"), sep = "/"),
          y_label_suffix = "B")

```
