---
output: reprex::reprex_document
knit: reprex::reprex_render
---

Notebook to run STURM Ouput.

```{r}
library(dplyr)
library(ggplot2)
library(stringr)
library(tidyr)

print(paste("Working directory is:", getwd()))

# Loding figures setttings and functions
source("STURM_output/C00_plots.R")


run_test <- TRUE
if (run_test) {
      run <- "scenarios_test"
      scenarios <- c(
        "EU_exogenous" = "Baseline",
        "EU_constant_exogenous" = "Price constant",
        "EU_price_2020_600_exogenous" = "Carbon tax",
        "EU_no_exogenous" = "No renovation",
        "EU_no_constant_exogenous" = "No renovation, Price constant",
        "EU_double_exogenous" = "Doubling renovation",
        "EU_double_constant_exogenous" =
          "Doubling renovation, Price constant",
        "EU_triple_exogenous" = "Tripling renovation",
        "EU_triple_constant_exogenous" =
          "Tripling renovation, Price constant",
        "EU_emission_1p5c_exogenous" = "Low emission factor",
        "EU_double_emission_1p5c_exogenous" =
          "Doubling renovation, Low emission factor",
        "EU_1p5c_exogenous" = "1p5C"
    ) } else {
    run <- "scenarios_policies"
    scenarios <- c(
        "EU" = "Baseline",
        "EU_constant" = "Price constant",
        "EU_1p5C" = "1p5C",
        "EU_ambitious_shell" = "Subsidies renovation",
        "EU_ambitious_heat" = "Subsidies heat-pumps")
    }

colors_scenarios <- c(
  "Baseline" = "#00589d",
  "Price constant" = "#247f6e",
  "Carbon tax" = "#fdbb40",
  "1p5C" = "#fdbb40",
  "Subsidies heat-pumps" = "#62c5c0",
  "Ambitious heat-pumps, price constant" = "#677473",
  "Subsidies renovation" = "#ee6a6b",
  "Ambitious renovation, prices constant" = "#531717",
  "Doubling renovation" = "#ee6a6b",
  "Doubling renovation, Price constant" = "#531717",
  "Tripling renovation" = "#380707",
  "Tripling renovation, Price constant" = "#531717",
  "No renovation" = "#6a4c93",
  "No renovation, Price constant" = "#531717",
  "Low emission factor" = "#2a9d00",
  "Doubling renovation, Low emission factor" = "#1f540b"
  )

```

## Read data
```{r}
save_dir <- paste("STURM_output", "figures", run, sep = "/")
if (!dir.exists(save_dir)) {
  dir.create(save_dir)
}

data <- data.frame(NULL)

for (scenario in names(scenarios)) {
  print(paste("Scenario:", scenario))
  file <- paste0("report_agg_STURM_", scenario, "_resid_region_bld_energy.csv")
  file <- paste("STURM_output/results", file, sep = "/")

  if (!file.exists(file)) {
    print("Check file name or directory!")
  }

  # Read output files
  temp <- read.csv(file) %>%
    mutate(scenario = scenario)
  
  data <- bind_rows(data, temp)
}
# Reconstuction flows
flows <- c("n_renovation", "cost_renovation_EUR",
  "n_replacement", "cost_heater_EUR")

data <- data %>%
  mutate(scenario = scenarios[.data[["scenario"]]])

stp <- 5

data <- data %>%
 mutate(year = ifelse(variable %in% flows, year - stp, year),
        value = ifelse(variable %in% flows, value / stp, value))
```

## Figures
### Table summary
```{r}
ref <- "Baseline"
base_year <- 2015
end_year <- 2050

variables <- c("heat_kWh", "heat_std_kWh", "heat_tCO2",
     "energy_poverty_thres", "stock_building", "n_replacement",
    "heating_intensity")

low_carbon <- c("biomass_solid", "heat_pump", "electricity", "district_heating")

ini <- data %>%
  filter(year == base_year) %>%
  filter(scenario == ref) %>%
  mutate(scenario = " Initial") %>%
  filter(resolution == "all") %>%
  filter(variable %in% variables) %>%
  select(-c("resolution", "year")) %>%
  pivot_wider(id_cols = c(region_bld, scenario),
    names_from = variable,
    values_from = value)

table <- data %>%
  filter(year == end_year) %>%
  filter(resolution == "all") %>%
  filter(variable %in% variables) %>%
  select(-c("resolution", "year")) %>%
  pivot_wider(id_cols = c(region_bld, scenario),
    names_from = variable,
    values_from = value)

table <- bind_rows(ini, table)

# replacement heating system
temp <- data %>%
  filter(year <= end_year) %>%
  filter(resolution == "all") %>%
  filter(variable == "n_replacement") %>%
  group_by_at(c("region_bld", "scenario")) %>%
  summarize(replacement_heater = sum(value) * stp) %>%
  ungroup()
table <- left_join(table, temp, by = c("region_bld", "scenario")) %>%
  mutate(replacement_heater =
    ifelse(is.na(replacement_heater), 0, replacement_heater))

# renovated buildings
temp <- data %>%
  filter(variable == "stock_building") %>%
  filter(year == end_year) %>%
  filter(resolution %in% c("std", "adv")) %>%
  select(-c("resolution", "year")) %>%
  group_by_at(c("region_bld", "scenario")) %>%
  summarize(renovated_building = sum(value)) %>%
  ungroup()

table <- left_join(table, temp, by = c("region_bld", "scenario")) %>%
  mutate(renovated_building =
    ifelse(is.na(renovated_building), 0, renovated_building))

temp <- data %>%
  filter(variable == "stock_building") %>%
  filter(year == end_year) %>%
  filter(resolution == "adv") %>%
  select(-c("resolution", "year")) %>%
  group_by_at(c("region_bld", "scenario")) %>%
  summarize(advanced_renovated_building = sum(value)) %>%
  ungroup()

table <- left_join(table, temp, by = c("region_bld", "scenario")) %>%
  mutate(advanced_renovated_building =
    ifelse(is.na(advanced_renovated_building), 0, advanced_renovated_building))


temp <- data %>%
  filter(variable == "stock_building") %>%
  filter(year == end_year) %>%
  filter(resolution %in% low_carbon) %>%
  group_by_at(c("region_bld", "scenario")) %>%
  summarize(low_carbon_building = sum(value)) %>%
  ungroup()
ini <- data %>%
  filter(variable == "stock_building") %>%
  filter(year == base_year) %>%
  filter(scenario == ref) %>%
  filter(resolution %in% low_carbon) %>%
  group_by_at(c("region_bld", "scenario")) %>%
  summarize(low_carbon_building = sum(value)) %>%
  ungroup() %>%
  mutate(scenario = " Initial")
temp <- bind_rows(ini, temp)

table <- left_join(table, temp, by = c("region_bld", "scenario")) %>%
  mutate(renovated_building =
    ifelse(is.na(renovated_building), 0, renovated_building))
    
format_temp <- table %>%
  arrange(region_bld, scenario) %>%
  mutate(,
    heat_kWh = round(heat_kWh / 1e9, 2),
    heat_std_kWh = round(heat_std_kWh / 1e9, 2),
    heat_tCO2 = round(heat_tCO2 / 1e6, 2),
    stock_building = round(stock_building / 1e3, 2),
    heating_intensity = round(heating_intensity, 2),
    renovated_building = round(renovated_building / 1e3, 2),
    advanced_renovated_building =
      round(advanced_renovated_building / 1e3, 2),
    replacement_heater = round(replacement_heater / 1e3, 2),
    low_carbon_building = round(low_carbon_building / 1e3, 2),
    energy_poverty_thres =
      round(energy_poverty_thres / 1e3, 2)) %>%
  mutate(region_bld = plot_settings[["rename"]][region_bld]) %>%
  select(c("region_bld", "scenario",
    "heat_kWh", "heat_std_kWh", "heat_tCO2",
    "heating_intensity", "stock_building", "low_carbon_building",
    "renovated_building", "advanced_renovated_building",
    "replacement_heater", "energy_poverty_thres")) %>%
  mutate(low_carbon_building_rate = low_carbon_building / stock_building,
    renovated_building_rate = renovated_building / stock_building,
    energy_poverty_rate = energy_poverty_thres / stock_building) %>%
  rename(
    "Energy poverty (Thousand)" = energy_poverty_thres,
    "Energy poverty (Percent)" = energy_poverty_rate,
    "Renovated buildings (Thousand)" = renovated_building,
    "Renovated buildings advanced (Thousand)" = advanced_renovated_building,
    "Renovated buildings (Percent)" = renovated_building_rate,
    "Low carbon buildings (Thousand)" = low_carbon_building,
    "Low carbon buildings (Percent)" = low_carbon_building_rate,
    "Stock building (Thousand)" = stock_building,
    "Replacement heating system (Thousand)" = replacement_heater,
    "Heating intensity (Percent)" = heating_intensity,
    "Space heating consumption (TWh)" = heat_kWh,
    "Space heating consumption standard (TWh)" = heat_std_kWh,
    "Emission (MtCO2)" = heat_tCO2,
    "Member states" = region_bld,
    "Scenario" = scenario)


write.csv(format_temp,
  paste(save_dir, paste0(run, "_", end_year, "_summary.csv"), sep = "/"),
  row.names = FALSE)
```


### Absolute values
#### Number of renovations
```{r}
source("STURM_output/C00_plots.R")


temp <- data %>%
  filter(variable == "n_renovation") %>%
  filter(resolution %in% "all") %>%
  select(-c("variable", "resolution")) %>%
  group_by(scenario, region_bld) %>%
  arrange(year) %>%
  mutate(value = cumsum(value)) %>%
  ungroup() %>%
  mutate(value = value * 5 / 1e3)

plot_multiple_lines(temp,
    x_column = "year",
    y_column = "value",
    line_column = "scenario",
    group_column = "region_bld",
    ncol = 4,
    y_label = "Cumulated number of renovations\nThousand",
    free_y = TRUE,
    colors_lines = colors_scenarios,
    save_path = paste(save_dir,
      paste0(run, "_renovation_cumulated_countries.png"), sep = "/"))

plot_multiple_lines(filter(temp, region_bld == "EU"),
    x_column = "year",
    y_column = "value",
    line_column = "scenario",
    group_column = NULL,
    ncol = 4,
    y_label = "Cumulated number of renovations\nThousand",
    free_y = TRUE,
    colors_lines = colors_scenarios,
    save_path = paste(save_dir,
      paste0(run, "_renovation_cumulated_eu.png"), sep = "/"))
```

#### Space heating consumption
```{r}
source("STURM_output/C00_plots.R")

temp <- data %>%
  filter(variable == "heat_kWh") %>%
  filter(resolution %in% "all") %>%
  select(-c("variable", "resolution")) %>%
  mutate(value = value / 1e9)

plot_multiple_lines(temp,
    x_column = "year",
    y_column = "value",
    line_column = "scenario",
    group_column = "region_bld",
    ncol = 4,
    y_label = "Consumtion\nTWh",
    free_y = TRUE,
    colors_lines = colors_scenarios,
    save_path = paste(save_dir,
      paste0(run, "_heat_kWh_countries.png"), sep = "/"))

plot_multiple_lines(filter(temp, region_bld == "EU"),
    x_column = "year",
    y_column = "value",
    line_column = "scenario",
    group_column = NULL,
    ncol = 4,
    y_label = "Consumtion\nTWh",
    free_y = TRUE,
    colors_lines = colors_scenarios,
    save_path = paste(save_dir,
      paste0(run, "_heat_kWh_eu.png"), sep = "/"))
```
```{r}
temp <- data %>%
  filter(variable == "heat_std_kWh") %>%
  filter(resolution %in% "all") %>%
  select(-c("variable", "resolution")) %>%
  mutate(value = value / 1e9)

plot_multiple_lines(temp,
    x_column = "year",
    y_column = "value",
    line_column = "scenario",
    group_column = "region_bld",
    ncol = 4,
    y_label = "Consumtion standard\nTWh",
    free_y = TRUE,
    colors_lines = colors_scenarios,
    save_path = paste(save_dir,
      paste0(run, "_heat_std_kWh_countries.png"), sep = "/"))

plot_multiple_lines(filter(temp, region_bld == "EU"),
    x_column = "year",
    y_column = "value",
    line_column = "scenario",
    group_column = NULL,
    ncol = 4,
    y_label = "Consumtion standard\nTWh",
    free_y = TRUE,
    colors_lines = colors_scenarios,
    save_path = paste(save_dir,
      paste0(run, "_heat_std_kWh_eu.png"), sep = "/"))
```
```{r}
temp <- data %>%
  filter(variable == "heat_tCO2") %>%
  filter(resolution %in% "all") %>%
  select(-c("variable", "resolution")) %>%
  mutate(value = value / 1e6)

plot_multiple_lines(temp,
    x_column = "year",
    y_column = "value",
    line_column = "scenario",
    group_column = "region_bld",
    ncol = 4,
    y_label = "Emission\nMtCO2",
    free_y = TRUE,
    colors_lines = colors_scenarios,
    save_path = paste(save_dir,
      paste0(run, "_heat_tCO2_countries.png"), sep = "/"))

plot_multiple_lines(filter(temp, region_bld == "EU"),
    x_column = "year",
    y_column = "value",
    line_column = "scenario",
    group_column = NULL,
    ncol = 4,
    y_label = "Emission\nMtCO2",
    free_y = TRUE,
    colors_lines = colors_scenarios,
    save_path = paste(save_dir,
      paste0(run, "_heat_tCO2_eu.png"), sep = "/"))

```
```{r}
temp <- data %>%
  filter(variable == "n_renovation") %>%
  filter(resolution %in% "all") %>%
  select(-c("variable", "resolution")) %>%
  mutate(value = value / 1e3)

plot_multiple_lines(temp,
    x_column = "year",
    y_column = "value",
    line_column = "scenario",
    group_column = "region_bld",
    ncol = 4,
    y_label = "Renovation\nThousands",
    free_y = TRUE,
    colors_lines = colors_scenarios,
    save_path = paste(save_dir,
      paste0(run, "_renovation_countries.png"), sep = "/"))

plot_multiple_lines(filter(temp, region_bld == "EU"),
    x_column = "year",
    y_column = "value",
    line_column = "scenario",
    group_column = NULL,
    ncol = 4,
    y_label = "Renovation\nThousands",
    free_y = TRUE,
    colors_lines = colors_scenarios,
    save_path = paste(save_dir,
      paste0(run, "_renovation_eu.png"), sep = "/"))

temp <- data %>%
  filter(variable == "stock_building") %>%
  filter(resolution %in% "heat_pump") %>%
  select(-c("variable", "resolution")) %>%
  mutate(value = value / 1e6)

plot_multiple_lines(temp,
    x_column = "year",
    y_column = "value",
    line_column = "scenario",
    group_column = "region_bld",
    ncol = 4,
    y_label = "Stock Heat-pumps\nMillion",
    free_y = TRUE,
    colors_lines = colors_scenarios,
    save_path = paste(save_dir,
      paste0(run, "_heat_pumps_countries.png"), sep = "/"))

plot_multiple_lines(filter(temp, region_bld == "EU"),
    x_column = "year",
    y_column = "value",
    line_column = "scenario",
    group_column = NULL,
    ncol = 4,
    y_label = "Stock Heat-pumps\nMillion",
    free_y = TRUE,
    colors_lines = colors_scenarios,
    save_path = paste(save_dir,
      paste0(run, "_heat_pumps_eu.png"), sep = "/"))
```

```{r}
temp <- data %>%
  filter(variable == "n_renovation") %>%
  filter(resolution %in% "all") %>%
  select(-c("variable", "resolution")) %>%
  mutate(value = value / 1e3)

plot_multiple_lines(temp,
    x_column = "year",
    y_column = "value",
    line_column = "scenario",
    group_column = "region_bld",
    ncol = 4,
    y_label = "Renovation\nThousands",
    free_y = TRUE,
    colors_lines = colors_scenarios,
    save_path = paste(save_dir,
      paste0(run, "_renovation_countries.png"), sep = "/"))
```

```{r}
temp <- data %>%
  filter(variable == "cost_renovation_EUR") %>%
  filter(resolution %in% "all") %>%
  select(-c("variable", "resolution")) %>%
  mutate(value = value / 1e9)

plot_multiple_lines(temp,
    x_column = "year",
    y_column = "value",
    line_column = "scenario",
    group_column = "region_bld",
    ncol = 4,
    y_label = "Cost Renovation\nBillion EUR",
    free_y = TRUE,
    colors_lines = colors_scenarios,
    save_path = paste(save_dir,
      paste0(run, "_cost_renovation_countries.png"), sep = "/"))

temp <- data %>%
  filter(variable == "cost_heater_EUR") %>%
  filter(resolution %in% "all") %>%
  select(-c("variable", "resolution")) %>%
  mutate(value = value / 1e9)

plot_multiple_lines(temp,
    x_column = "year",
    y_column = "value",
    line_column = "scenario",
    group_column = "region_bld",
    ncol = 4,
    y_label = "Cost Heating system\nBillion EUR",
    free_y = TRUE,
    colors_lines = colors_scenarios,
    save_path = paste(save_dir,
      paste0(run, "_cost_heater_countries.png"), sep = "/"))
````

```{r}
temp <- data %>%
  filter(variable == "cost_heat_EUR") %>%
  filter(resolution %in% "all") %>%
  select(-c("variable", "resolution")) %>%
  mutate(value = value / 1e9)

plot_multiple_lines(temp,
    x_column = "year",
    y_column = "value",
    line_column = "scenario",
    group_column = "region_bld",
    ncol = 4,
    y_label = "Cost Heating\nBillion EUR",
    free_y = TRUE,
    colors_lines = colors_scenarios,
    save_path = paste(save_dir,
      paste0(run, "_cost_heat_countries.png"), sep = "/"))

plot_multiple_lines(filter(temp, region_bld == "EU"),
    x_column = "year",
    y_column = "value",
    line_column = "scenario",
    group_column = NULL,
    ncol = 4,
    y_label = "Cost Heating\nBillion EURn",
    free_y = TRUE,
    colors_lines = colors_scenarios,
    save_path = paste(save_dir,
      paste0(run, "_cost_heat_eu.png"), sep = "/"))

```

### Indicators comparison

#### Unit consumption
```{r}
var <- "heat_kWh"
ref <- "floor_m2"
path <- "_kwh_m2_countries.png"
y_label <- "Space heating consumption\nkWh per square meter"

temp <- data %>%
  filter(variable %in% c(var, ref)) %>%
  filter(resolution == "all") %>%
  pivot_wider(id_cols = c(region_bld, year, scenario, resolution),
    names_from = variable,
    values_from = value) %>%
  filter(!is.na(.data[[var]])) %>%
  filter(!is.na(.data[[ref]])) %>%
  mutate(value = .data[[var]] / .data[[ref]]) %>%
  select(-c(var, ref, "resolution"))


plot_multiple_lines(temp,
    x_column = "year",
    y_column = "value",
    line_column = "scenario",
    group_column = "region_bld",
    ncol = 4,
    y_label = y_label,
    free_y = TRUE,
    colors_lines = colors_scenarios,
    save_path = paste(save_dir,
      paste0(run, path), sep = "/"))

path <- "_kwh_m2_eu.png"
temp <- filter(temp, region_bld == "EU")
plot_multiple_lines(temp,
    x_column = "year",
    y_column = "value",
    line_column = "scenario",
    group_column = NULL,
    ncol = 4,
    y_label = y_label,
    free_y = TRUE,
    colors_lines = colors_scenarios,
    save_path = paste(save_dir,
      paste0(run, path), sep = "/"))
```

#### Renovation rate

```{r}
var <- "n_renovation"
ref <- "stock_building"
path <- "_renovation_rate_countries.png"
y_label <- "Renovation rate"

temp <- data %>%
  filter(variable %in% c(var, ref)) %>%
  filter(resolution == "all") %>%
  pivot_wider(id_cols = c(region_bld, year, scenario, resolution),
    names_from = variable,
    values_from = value) %>%
  filter(!is.na(.data[[var]])) %>%
  filter(!is.na(.data[[ref]])) %>%
  mutate(value = .data[[var]] / .data[[ref]]) %>%
  select(-c(var, ref, "resolution"))


plot_multiple_lines(temp,
    x_column = "year",
    y_column = "value",
    line_column = "scenario",
    group_column = "region_bld",
    ncol = 4,
    y_label = y_label,
    free_y = FALSE,
    colors_lines = colors_scenarios,
    save_path = paste(save_dir,
      paste0(run, path), sep = "/"))

path <- "_renovation_rate_eu.png"
temp <- filter(temp, region_bld == "EU")
plot_multiple_lines(temp,
    x_column = "year",
    y_column = "value",
    line_column = "scenario",
    group_column = NULL,
    ncol = 4,
    y_label = y_label,
    free_y = FALSE,
    colors_lines = colors_scenarios,
    save_path = paste(save_dir,
      paste0(run, path), sep = "/"))
```

#### Energy poverty

```{r}
var <- "energy_poverty_median"
ref <- "stock_building"
path <- "_energy_poverty_median_countries.png"
y_label <- "Energy poverty rate with median definition"

temp <- data %>%
  filter(variable %in% c(var, ref)) %>%
  filter(resolution == "all") %>%
  pivot_wider(id_cols = c(region_bld, year, scenario, resolution),
    names_from = variable,
    values_from = value) %>%
  filter(!is.na(.data[[var]])) %>%
  filter(!is.na(.data[[ref]])) %>%
  mutate(value = .data[[var]] / .data[[ref]]) %>%
  select(-c(var, ref, "resolution"))


plot_multiple_lines(temp,
    x_column = "year",
    y_column = "value",
    line_column = "scenario",
    group_column = "region_bld",
    ncol = 4,
    y_label = y_label,
    free_y = FALSE,
    colors_lines = colors_scenarios,
    save_path = paste(save_dir,
      paste0(run, path), sep = "/"))

```

```{r}
var <- "energy_poverty_thres"
ref <- "stock_building"
path <- "_energy_poverty_threshold_countries.png"
y_label <- "Energy poverty rate with threshold definition"

temp <- data %>%
  filter(variable %in% c(var, ref)) %>%
  filter(resolution == "all") %>%
  pivot_wider(id_cols = c(region_bld, year, scenario, resolution),
    names_from = variable,
    values_from = value) %>%
  filter(!is.na(.data[[var]])) %>%
  filter(!is.na(.data[[ref]])) %>%
  mutate(value = .data[[var]] / .data[[ref]]) %>%
  select(-c(var, ref, "resolution"))


plot_multiple_lines(temp,
    x_column = "year",
    y_column = "value",
    line_column = "scenario",
    group_column = "region_bld",
    ncol = 4,
    y_label = y_label,
    free_y = FALSE,
    colors_lines = colors_scenarios,
    save_path = paste(save_dir,
      paste0(run, path), sep = "/"))

path <- "_energy_poverty_threshold_eu.png"
plot_multiple_lines(filter(temp, region_bld == "EU"),
    x_column = "year",
    y_column = "value",
    line_column = "scenario",
    group_column = NULL,
    ncol = 4,
    y_label = y_label,
    free_y = TRUE,
    colors_lines = colors_scenarios,
    save_path = paste(save_dir,
      paste0(run, path), sep = "/"))

```