---
output: reprex::reprex_document
knit: reprex::reprex_render
---

Notebook to run STURM Ouput.
Description of the building stock and energy consumption.
Without calibrating energy consumption.
Check description_stock_agg for calibrating results.

```{r}
library(dplyr)
library(ggplot2)
library(stringr)
library(tidyr)


print(paste("Working directory is:", getwd()))

# Loding figures setttings and functions
source("STURM_output/C00_plots.R")
```

## Read output files
```{r}
scenario <- "EU_exogenous"
file <- paste0("report_agg_STURM_", scenario, "_resid_region_bld_energy.csv")
file <- paste("STURM_output/results", file, sep = "/")

if (!file.exists(file)) {
  print("Check file name or directory!")
}

# Read output files
data_full <- read.csv(file)
print(summary(data_full))


# Export figures and tables
save_figs <- paste("STURM_output", "figures", sep = "/")
save_tables <- paste("STURM_output", "tables", sep = "/")

print(dir.exists(save_figs))
print(dir.exists(save_tables))

```

```{r}
data <- filter(data_full, year == 2015) %>%
  filter(variable %in% c("stock_building", "floor_m2", "heat_kWh", "heat_tCO2")) %>%
  filter(resolution == "all")

data <- pivot_wider(data,
                    id_cols = c("region_bld", "year", "resolution"),
                    names_from = variable,
                    values_from = value)
```

## Table about the distribution
```{r}

# Total energy consumption
report <- data %>%
  mutate(
    floor_hh = floor_m2 / stock_building,
    heat_hh_kWh = heat_kWh / stock_building,
    heat_hh_toe = heat_hh_kWh / (11.63 * 1e3),
    heat_floor_kWh = heat_kWh / floor_m2,
    heat_floor_koe = heat_floor_kWh / 11.63,
    stock_building = stock_building / 1e6,
    heat_tCO2_m2 = heat_tCO2 / floor_m2,
    floor_m2 = floor_m2 / 1e6,
    heat_mtoe = heat_kWh / 11630 / 1e6,
    heat_TJ = heat_kWh * 3.6 / 1e6,
    heat_kWh = heat_kWh / 1e9,
    heat_tot_mtoe = heat_kWh / 11.63,
    heat_tCO2 = heat_tCO2 / 1e6

  ) %>%
  rename(
    "n_units (M)" = stock_building,
    "floor (M m2)" = floor_m2,
    "heat (TWh)" = heat_kWh,
    "heat (Mtoe)" = heat_mtoe,
    "heat (TJ)" = heat_TJ,
    "floor_hh (m2/hh)" = floor_hh,
    "heat_hh (kWh/hh)" = heat_hh_kWh,
    "heat_hh (toe/hh)" = heat_hh_toe,
    "heat_floor (koe/m2)" = heat_floor_koe,
    "heat_floor (kWh/m2)" = heat_floor_kWh,
    "heat emission (MtCO2)" = heat_tCO2,
    "heat emission (tCO2/m2)" = heat_tCO2_m2
  ) %>%
  select(c("region_bld", "n_units (M)", "floor (M m2)", "floor_hh (m2/hh)",
    "heat (TWh)", "heat (Mtoe)", "heat (TJ)",
    "heat_hh (kWh/hh)", "heat_hh (toe/hh)",
    "heat_floor (koe/m2)", "heat_floor (kWh/m2)",
    "heat emission (MtCO2)", "heat emission (tCO2/m2)"))

write.csv(report, paste(save_tables,
  paste0("description_ini_agg.csv"), sep = "/"), row.names = FALSE)

```

