```{r reprex-options, include = FALSE}
options(
  keep.source = TRUE,
  rlang_backtrace_on_error_report = "full",
  crayon.enabled = FALSE,
  reprex.current_venue = "gh"
)
```

```{r, results = 'asis', echo = FALSE, include = file.exists('.Rprofile'), eval = file.exists('.Rprofile')}
cat(sprintf("*Local `.Rprofile` detected at `%s`*", normalizePath(".Rprofile")))
```

---
output: reprex::reprex_document
knit: reprex::reprex_render
---

Notebook to run STURM Ouput.

```{r}
library(dplyr)
library(ggplot2)
library(stringr)

print(paste("Working directory is:", getwd()))

# Loding figures setttings and functions
source("STURM_output/plot_settings.R")

```

```{r}
file <- "report_STURM_EU_implementation_resid_region_bld_energy.csv"
file <- paste("STURM_output", file, sep = "/")

if (!file.exists(file)) {
  print("Check file name or directory!")
}

save_dir <- paste("STURM_output", "figures", sep = "/")
print(dir.exists(save_dir))
```

```{r}
# Read output files
data <- read.csv(file)
print(summary(data))
```

## Data formatting
```{r}
data <- data %>%
    mutate(heat_TWh = heat_TJ / 3.6 / 10^3) %>%
    mutate(heat_hh_kWh = heat_TWh * 10**3 / stock_M)
```

## Figures
```{r}
plot_variable_evolution(data,
                        x_column = "year",
                        y_column = "heat_TWh",
                        group_column = "region_bld",
                        subplot = TRUE,
                        save_path = paste(save_dir, "heat_evolution.png", sep="/"))
```

## Stock of households by space heating fuels
```{r}
plot_stacked_area(data, "year", "stock_M", "fuel_heat",
                  y_label = "Stock households\nMillion buildings",
                  save_path = paste(save_dir, "stock_hh_fuel.png", sep="/"))
```

## Final energy consumption for space heating in the Residential sector (TWh)
```{r}
plot_stacked_area(data, "year", "heat_TWh", "fuel_heat",
                  save_path = "figures/heating_fuel.png",
                  y_label = "Final energy consumption for space heating \nResidential sector\nTWh",
                  font_size = 11)
```


<sup>Created on `r Sys.Date()` with [reprex v`r utils::packageVersion("reprex")`](https://reprex.tidyverse.org)</sup>
