#' This script is used to analyze the results of the scenarios and generate the figures.
#' It uses result.csv file generated by the post_traitment function.

library(tidyverse)
library(dplyr)
library(ggplot2)
library(stringr)
library(gridExtra)

source("STURM_output/C00_plots.R")
# Load data
dir <- "2024-06-26_091653"
save_dir <- paste("STURM_output", "figures", dir, sep = "/")
file <- paste(save_dir, "results.csv", sep = "/")
data <- read.csv(file,  check.names = FALSE, stringsAsFactors = FALSE, header = TRUE, row.names = NULL)
data <- data[, -1]

out_dir <- paste(save_dir, "standalone", sep = "/")
if (!dir.exists(out_dir)) {
    dir.create(out_dir)
}

scenarios <- c(
    "Baseline", "EU-ETS", "EU-ETS 2", "Social value of carbon",
    "Subsidies heat pumps", "Subsidies heat pumps medium", "Market-failures heater",
    "Learning-by-doing heat pumps",
    "Renovation wave", "Renovation wave half success",
    "Deep renovation wave", "Deep renovation wave half success",
    "Quality renovation",
    "Market-failures renovation")

rename_scenarios <- c(
  "Baseline" = "Baseline",
  "EU-ETS" = "ETS2-Aligned ETS Price",
  "Social value of carbon" = "ETS2-Aligned Carbon Value",
  "Subsidies heat pumps" = "High heat pumps subsidies",
  "Subsidies heat pumps medium" = "Mid heat pumps subsidies",
  "Learning-by-doing heat pumps" = "Learning-by-doing heat pumps",
  "Renovation wave" = "High renovation subsidies",
  "Renovation wave half success" = "Mid renovation subsidies",
  "Deep renovation wave" = "High Deep renovation subsidies",
  "Deep renovation wave half success" = "Mid Deep renovation subsidies",
  "Quality renovation" = "Improvement renovation realization",
  "Market-failures renovation" = "Tackling investment barriers"
)
scenarios <- unname(rename_scenarios)

carbon_tax <- c("ETS2-Aligned ETS Price", "ETS2-Aligned Carbon Value")
heat_pumps <- c("High heat pumps subsidies", "Mid heat pumps subsidies", "Learning-by-doing heat pumps")
renovation <- c("High renovation subsidies", "Mid renovation subsidies", "High Deep renovation subsidies",
  "Mid Deep renovation subsidies", "Improvement renovation realization", "Tackling investment barriers")


# Select scenario by rows
subset <- data %>%
    filter(group %in% names(rename_scenarios)) %>%
    mutate(group = ifelse(group %in% names(rename_scenarios), rename_scenarios[group], group))


# Export as .csv
write.csv(subset, paste(out_dir, "results_standalone.csv", sep = "/"), row.names = FALSE)

#-----------------------------------
# Make heatmap of the results
cols <- c(
    "Space heating consumption (TWh)",
    "Space heating consumption electricity (TWh)",
    "Emission (MtCO2)", "Emission cumulated (GtCO2)",
    "Total cost (Billion EUR)",
    "Government expenditures (Billion EUR)",
    "Delta total cost private (euro/hh/year)",
    "Delta total cost (euro/hh/year)",
    "Energy poverty (Percent)")

# Calculate the percentage of the total cost compared to the counterfactual
cost_counterfactual <- subset %>%
  filter(group == "Baseline") %>%
  select(`Delta total cost (euro/hh/year)`) %>%
  pull()

emission_counterfactual <- subset %>%
  filter(group == "Baseline") %>%
  select(`Emission saving (%)`) %>%
  pull()

energy_counterfactual <- subset %>%
  filter(group == "Baseline") %>%
  select(`Consumption saving (%)`) %>%
  pull()

electricity_counterfactual <- subset %>%
  filter(group == "Baseline") %>%
  select(`Consumption electricity variation (%)`) %>%
  pull()

energy_poverty_counterfactual <- subset %>%
  filter(group == "Baseline") %>%
  select(`Energy poverty (Percent)`) %>%
  pull()


cols <- c(
  "Emission saving (%)" = "Emission",
  "Consumption saving (%)" = "Energy use",
  "Consumption electricity variation (%)" = "Electricity use",
  "Energy poverty (Percent)" = "Energy poverty"
)


temp <- subset %>%
    select(all_of(c("group", names(cols)))) %>%
    pivot_longer(cols = -group, names_to = "variable", values_to = "value") %>%
    #filter(group != "Counterfactual")
    # Replace NaN with 0
    mutate(value = ifelse(is.na(value), 0, value)) %>%
    rename(scenario = group) %>%
    mutate(value = ifelse((scenario != "Baseline") & (variable == "Emission saving (%)" ), value + emission_counterfactual, value)) %>%
    mutate(value = ifelse((scenario != "Baseline") & (variable == "Consumption saving (%)"), value + emission_counterfactual, value)) %>%
    mutate(value = ifelse((scenario != "Baseline") & (variable == "Consumption electricity variation (%)"), value + emission_counterfactual, value)) %>%
    mutate(value = ifelse((scenario != "Baseline") & (variable == "Energy poverty (Percent)"), value + energy_poverty_counterfactual, value)) %>%
    # Rename colnames with cols
    mutate(value = ifelse(variable %in% c("Emission saving (%)", "Consumption saving (%)"), - value, value)) %>%
    mutate(variable = ifelse(variable %in% names(cols), cols[variable], variable)
    )


temp <- temp %>%
    mutate(groups = case_when(
        scenario == "Baseline" ~ "",
        scenario %in% carbon_tax ~ "Carbon tax",
        scenario %in% heat_pumps ~ "Promoting Heat pumps",
        scenario %in% renovation ~ "Promoting Energy Renovation",
        TRUE ~ "Other"
    ))


# Order groups c("", "Carbon tax", "Promoting Heat pumps", "Promoting Energy Renovation") for figures
temp$groups <- factor(temp$groups, levels = c("", "Carbon tax", "Promoting Heat pumps", "Promoting Energy Renovation"))


temp$variable <- factor(temp$variable, levels = cols)
# Reverse order compare to scenarios
temp$scenario <- factor(temp$scenario, levels = rev(scenarios))


limits <- c(-1, 1)

max_values <- temp %>%
  group_by(variable) %>%
  summarise(max_value = max(abs(value), na.rm = TRUE))

temp <- temp %>%
  left_join(max_values, by = "variable") %>%
   mutate(norm_value = value / max_value)

# Create heatmap
p <- temp %>%
  ggplot(aes(x = variable, y = scenario)) +
  geom_tile(aes(fill = norm_value), color = "white", height = 1, width = 0.95) +
  # geom_text(aes(label = paste0(round(value * 100, 1), "%")), size = 6) +
  geom_text(aes(label = paste0(round(value * 100, 1), "%"), 
                fontface = ifelse(abs(value) == max_value, "bold", "plain")),
            size = 7) +
  scale_fill_gradient2(
    low = "#2166AC",     # Blue
    mid = "white",       
    high = "#B2182B",    # Red-orange
    midpoint = 0,
    limits = limits,
    oob = scales::squish,
    na.value = "grey"
    ) +
  theme_minimal() +
    theme(axis.title.y = element_blank(),
      axis.title.x.top = element_blank(),
      axis.text.x.top = element_text(size = 25, angle = 0, face = "bold"),
      axis.text.y = element_text(size = 20),
      panel.spacing = unit(0.5, "lines"),  # Adjust spacing between panels
      legend.position = "none") +
  scale_x_discrete(position = "top") +
  facet_grid(groups ~ ., scales = "free_y", space = "free_y", switch = "y") +
  theme(strip.background = element_blank(),
      strip.placement = "outside",
      strip.text.y = element_text(size = 20, face = "bold", angle = 0, hjust = 0.5))

# save plot
ggsave(filename = paste(out_dir, "heatmap.png", sep = "/"), plot = p,
    width = plot_settings[["width"]],
    height = plot_settings[["height"]],
    dpi = plot_settings[["dpi"]])

# save data
t <- temp %>%
  select(scenario, variable, value) %>%
  spread(variable, value)
write.csv(t, paste(out_dir, "heatmap.csv", sep = "/"), row.names = FALSE)

#-----------------------------------
# Make cost-benefits analysis
rename_list <- c(
  `Delta cost renovation (euro/hh/year)` = "Cost renovation",
  `Delta cost heating system (euro/hh/year)` = "Cost heating system",
  `Delta cost fuel (euro/hh/year)` = "Cost fuel",
  `Delta cost thermal comfort (euro/hh/year)` = "Cost thermal comfort",
  `Delta total cost private (euro/hh/year)` = "Total cost private",
  `Delta cost emission (euro/hh/year)` = "Cost emission",
  `Delta total cost (euro/hh/year)` = "Total cost"
)

color_list <- c(
  "Cost renovation" = "#ee6a6b",
  "Cost heating system" = "#62c5c0",
  "Cost fuel" = "#00589d",
  "Cost emission" = "#fdbb40",
  "Cost thermal comfort" = "lightblue"
)

df <- subset %>%
  rename(scenario = group) %>%
    # Select only the relevant columns based on the rename_list
  select(scenario, `Delta cost renovation (euro/hh/year)`,
          `Delta cost heating system (euro/hh/year)`, `Delta cost fuel (euro/hh/year)`,
          `Delta cost thermal comfort (euro/hh/year)`, `Delta total cost (euro/hh/year)`, 
          `Delta total cost private (euro/hh/year)`, `Delta cost emission (euro/hh/year)`) %>%
  gather(variable, value, `Delta cost renovation (euro/hh/year)`,
         `Delta cost heating system (euro/hh/year)`, `Delta cost fuel (euro/hh/year)`,
         `Delta cost thermal comfort (euro/hh/year)`, `Delta total cost (euro/hh/year)`, 
         `Delta total cost private (euro/hh/year)`, `Delta cost emission (euro/hh/year)`) %>%
  mutate(variable = rename_list[.data[["variable"]]]) %>%
  filter(scenario != "Baseline") %>%
  # mutate(scenario = scenarios[.data[["scenario"]]]) %>%
  mutate(value = value)

df$scenario  <- factor(df$scenario, levels = rev(scenarios))


total <- df %>%
  filter(variable == "Total cost") %>%
  rename(total_value = value) %>%
  select(-variable)

total_private <- df %>%
  filter(variable == "Total cost private") %>%
  rename(total_value_private = value) %>%
  select(-variable)

df <- df %>%
  filter(variable != "Total cost", variable != "Total cost private")

df <- df %>%
  left_join(total) %>%
  left_join(total_private) %>%
  mutate(groups = case_when(
    scenario == "Baseline" ~ "",
    scenario %in% carbon_tax ~ "Carbon tax",
    scenario %in% heat_pumps ~ "Promoting Heat pumps",
    scenario %in% renovation ~ "Promoting Energy Renovation",
    TRUE ~ "Other"
  ))

df <- df %>%
  mutate(groups = factor(groups, levels = c("", "Carbon tax", "Promoting Heat pumps", "Promoting Energy Renovation")))


save_path <- paste(out_dir, "cba_eu_horizontal.png", sep = "/")
size_text <- 8
size_point <- 5
nudge_y <- 0.15
round <- 0

p <- df %>%
  ggplot(aes(x = scenario, y = value, fill = variable)) +
  geom_bar(stat = "identity") +
  geom_point(aes(x = scenario, y = total_value),
    color = "black", size = size_point, , show.legend = FALSE) +
  geom_text(aes(x = scenario,
    label = paste(round(total_value, round)), y = total_value),
    vjust = -0.5, nudge_y = nudge_y, size = size_text)+ 
  geom_point(aes(x = scenario, y = total_value_private),
    color = "red", size = size_point, shape = 18, show.legend = FALSE) +
  geom_text(aes(x = scenario,
    label = paste(round(total_value_private, round)), y = total_value_private),
    vjust = 1.5, nudge_y = - nudge_y, size = size_text, color = "red") + 
  coord_flip() + 
  scale_fill_manual(values = color_list) + 
  message_building_theme +
  theme(axis.line.y = element_blank()) +
  facet_grid(groups ~ ., scales = "free_y", space = "free_y", switch = "y") +
  theme(strip.background = element_blank(),
      strip.placement = "outside",
      strip.text.y = element_text(size = 20, face = "bold", angle = 0, hjust = 0.5)) 


ggsave(save_path, plot = p, width = plot_settings[["width"]],
        height = plot_settings[["height"]],
        dpi = plot_settings[["dpi"]])

# save data
t <- df %>%
  select(scenario, variable, value) %>%
  spread(variable, value)

write.csv(t, paste(out_dir, "cba_eu.csv", sep = "/"), row.names = FALSE)

print('Done')

# Custom label function that combines comma and suffix
# custom_label <- function(x) {
#   label_comma()(x) %>% paste0(" ", y_label_suffix)
# }
# p <- p +
#   scale_y_continuous(labels = custom_label)

# stacked_plots(df,
# save_path = paste(out_dir, "cba_eu.png", sep = "/"),
# color_list = color_list, y_label_suffix = "", # EUR/(year.hh)
# presentation = presentation, legend = legend)

# stacked_plots(df,
# save_path = ,
# color_list = color_list, y_label_suffix = "", #EUR/(year.hh)
# presentation = presentation, legend = legend, horizontal = TRUE)


#-----------------------------------